# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['sigla']},
        ),
    ]
