# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_auto_20171228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla'),
        ),
    ]
