# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfamero da pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='numero_exibicoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de vezes que a pergunta foi realizada'),
        ),
    ]
