# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legenda', models.CharField(max_length=250, verbose_name='Legenda')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('\xc1UDIO', '\xc1udio')], default='TEXTO', max_length=7, verbose_name='Tipo de m\xeddia')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
