# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='arquivo',
            field=models.TextField(blank=True, null=True, verbose_name='Caminho do arquivo'),
        ),
    ]
