# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0002_midia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/midias', verbose_name='Arquivo anexo'),
        ),
    ]
