# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuria',
            name='descricao',
            field=models.TextField(verbose_name='descricao'),
        ),
    ]
