# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
        ('injuria', '0002_auto_20171231_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuria',
            name='midia_texto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='midia.Midia'),
        ),
    ]
