# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuria', '0003_injuria_midia_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuria',
            name='descricao',
            field=models.TextField(verbose_name='Descri\xe7\xe3o da inj\xfaria'),
        ),
        migrations.AlterField(
            model_name='injuria',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome principal da inj\xfaria'),
        ),
    ]
