# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20171228_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=70, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text=b'Se ativo o usu\xc3\xa1rio tem permiss\xc3\xa3o para acessar o sistema', verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='nome'),
        ),
    ]
