# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_auto_20171229_1645'),
        ('usuario', '0004_auto_20171229_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Instituicao'),
        ),
    ]
